name: build_and_test_app
on:
  workflow_dispatch: 

jobs:
  build:  
    runs-on: ubuntu-latest
    steps:
      - run: echo "succesfull build"
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - run: echo "all tests passed"
