name: blue_green_switcher

on:
    workflow_dispatch:
    workflow_run:
        workflows: ["build_and_test_app"]
        types:
        - completed
        
jobs:
    log_succesuflly_triggered: 
        runs-on: ubuntu-latest
        environment: blue-green
        steps:
        - run: echo "switcher triggered after build-test completed succesfully (or manually for test purposes)"
        - run: echo "should be trigger if no failed tests and completed succesfully"
        - run: echo ${{env.path_to_deploy}}
